#! /bin/sh

#--------------------------------------------------
# option
#

PLAYER=`which rcsslogplayer 2> /dev/null`
if test $? -eq 1; then
    echo "Error: rcsslogplayer can not be found in your PATH"
    echo ""
    exit 1
fi


X=0
for PARAM in "$@"; do
    case "$PARAM" in
        -frameview)
        MON=`which rcssmonitor 2> /dev/null`

        if test $? -eq 1; then
            echo "Error: rcssmonitor found in your PATH"
            echo ""
            exit 1
        fi
        ;;
        -classic)
        MON=`which rcssmonitor_classic 2> /dev/null`
        if test $? -eq 1; then
            echo "Error: rcssmonitor_classic found in your PATH"
            echo ""
            exit 1
        fi
        ;;
        *)
        PARAMS[$X]=$PARAM
        X=$X+1
        ;;
    esac
done

if test -z "$MON"; then
    if test "$RCSSMONITOR"; then
        MON=`which "$RCSSMONITOR" 2> /dev/null`
        if test $? -eq 1; then
            echo "Error: cannot find the monitor specified by RCSSMONITOR: $RCSSMONITOR"
            echo ""
            exit 1
        fi
    else
        MON=`which rcssmonitor 2> /dev/null`
        if test $? -eq 1; then
            MON=`which rcssmonitor_classic 2> /dev/null`
            if test $? -eq 1; then
                echo "Error: No monitors can be found in your PATH and the"
                echo "       RCSSMONITOR environment variable is not set. Please"
                echo "       add rcssmonitor or rcssmonitor_classic to you PATH,"
                echo "       or set the RCSSMONITOR environment variable to the"
                echo "       executable you wish to use."
                echo ""
                exit 1
            fi
        fi
    fi
fi






#--------------------------------------------------
# set handler
#

trap kill_player INT

#--------------------------------------------------
# start server
#

echo "Starting logplayer..."

$PLAYER "${PARAMS[@]}" &
PID=$!

#--------------------------------------------------
# kill player
#
kill_player()
{
    kill -s INT $PID
    echo ""
    exit 0
}

#--------------------------------------------------
# start monitor
#

sleep 1

echo "Starting monitor..."

$MON

kill_player
